# basic options,I can say what ever here
title: Code-Coffee
author: Nickolas Fuentes
email: nickolasfuen@gmail.com
description: Documenting my coding journey as I learn and achieve
twitter_username: nickolas_fuen
github_username: nickfuentes

# Build settings
markdown: kramdown
theme: minima
