# basic options
title: Code-Coffee
author: Nickolas Fuentes
email: nickolasfuen@gmail.com
description: Documenting my knowledge of frameworks, architectures and languages.
twitter_username: nickolas_fuen
github_username: nickfuentes

# Build settings
markdown: kramdown
theme: minima
